<a href="https://colab.research.google.com/github/wbjeon2k/pytorchbookExcercise/blob/master/AIHW1_Grad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://tutorials.pytorch.kr/beginner/pytorch_with_examples.html
# -*- coding: utf-8 -*-
import numpy as np
import math

#input data given in HW1

#x_i = [1, x_i0, x_i1]
x = np.array(
    [[1,1,2],
     [1,2,1],
     [1,3,2],
     [1,3,3],
     [1,4,5]])
y = np.array([6,4,7,10,10])



In [ ]:


# theta_0 = [0,0,0]
a = 0
b = 0
c = 0

def get_loss():
    ret = 0 
    #get squared loss
    for t in range(5):
        x_t = x[t]
        y_pred = a*x_t[0] + b*x_t[1] + c*x_t[2]
        #print(f'y_pred{t} = {y_pred}')
        #L2 squared loss
        ret += (y_pred - y[t])*(y_pred - y[t])
    return ret

learning_rate = 1e-2
for t in range(5):
    # 순전파 단계: 예측값 y를 계산합니다
    # a = theta_0
    # b = theta_1
    # c = theta_2
    # y = ax[0] + bx[1] + cx[2]
    datanum = t
    print(f'{t}th learning')
    print(f'start with parameters {a}, {b}, {c}, learning rate {learning_rate}')

    # 손실(loss)을 계산하고 출력합니다
    loss = get_loss()
    print(f'loss {loss}')     

    # 손실에 따른 a, b, c의 변화도(gradient)를 계산하고 역전파합니다.
    grad_y_pred = np.zeros(3)
    for i in range(5):
        x_i = x[i]
        y_hat = a * x_i[0] + b * x_i[1] + c * x_i[2]
        for j in range(3):
            #grad[j] = 2*(y_hat - y)*x_i[j] for all i
            print(f'i: {i}, j:{j}')
            #print(f"j {j} yhat {y_hat}, y[i] {y[i]}, x_i[j] {x_i[j]}")
            tmp= 2.0 * (y_hat - y[i]) * x_i[j]
            print(f'2.0 * (y_hat - y[i]) * x_i[j] = 2*({y_hat} - {y[i]})*{x_i[j]} = {tmp}')
            grad_y_pred[j] += tmp
    
    print(grad_y_pred)
    grad_a = grad_y_pred[0] #x_t[0] is always 1
    grad_b = grad_y_pred[1]
    grad_c = grad_y_pred[2]
    print(f'grad: grad_a {grad_a}, grad_b {grad_b},  grad_c {grad_c}')

    # 가중치를 갱신합니다.
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    print(f'updated parameters: {a}, {b}, {c}')
    print("\n")

#final parameters:
print(f'final parameters: {a}, {b}, {c}\n')
print(f'final loss: {get_loss()}')
#get final loss for data 1~5
for t in range(5):
    x_t = x[t]
    #print(f'x[0] {x_t[0]}, x[1] {x_t[1]}, x[0] {x_t[2]}')
    y_pred = a * x_t[0] + b * x_t[1] + c * x_t[2]
    print(f'{t}th loss, y_pred {y_pred}, y_label {y[t]}')

0th learning
start with parameters 0, 0, 0, learning rate 0.01
loss 301
i: 0, j:0
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 6)*1 = -12.0
i: 0, j:1
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 6)*1 = -12.0
i: 0, j:2
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 6)*2 = -24.0
i: 1, j:0
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 4)*1 = -8.0
i: 1, j:1
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 4)*2 = -16.0
i: 1, j:2
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 4)*1 = -8.0
i: 2, j:0
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 7)*1 = -14.0
i: 2, j:1
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 7)*3 = -42.0
i: 2, j:2
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 7)*2 = -28.0
i: 3, j:0
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 10)*1 = -20.0
i: 3, j:1
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 10)*3 = -60.0
i: 3, j:2
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 10)*3 = -60.0
i: 4, j:0
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 10)*1 = -20.0
i: 4, j:1
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 10)*4 = -80.0
i: 4, j:2
2.0 * (y_hat - y[i]) * x_i[j] = 2*(0 - 10)*5 = 

In [ ]:
#get pseudoinverse

xT = np.transpose(x)
print("xT:")
print(xT)

xTx = np.matmul( xT, x)
print("xTx:")
print(xTx)

xTx_inverse = np.linalg.inv(xTx)
print("xTx_inverse:")
print(xTx_inverse)

print("theta_star:")
theta_star = np.linalg.multi_dot([xTx_inverse,xT,y])
print(theta_star)

def get_loss2():
    ret = 0 
    #get squared loss
    for t in range(5):
        x_t = x[t]
        y_pred = theta_star[0]*x_t[0] + theta_star[1]*x_t[1] + theta_star[2]*x_t[2]
        ret += (y_pred - y[t])*(y_pred - y[t])
    return ret

print(f'Loss: {get_loss2()}')

#https://www.wolframalpha.com/input/?i=matrix+calculator&assumption=%7B%22F%22%2C+%22MatricesOperations%22%2C+%22theMatrix3%22%7D+-%3E%22%5B6%2C4%2C7%2C10%2C10%5D%22&assumption=%7B%22F%22%2C+%22MatricesOperations%22%2C+%22theMatrix2%22%7D+-%3E%22%5B%5B1%2C1%2C1%2C1%2C1%5D+%2C%5B1%2C2%2C3%2C3%2C4%5D+%2C%5B2%2C1%2C2%2C3%2C5%5D%5D%22&assumption=%7B%22F%22%2C+%22MatricesOperations%22%2C+%22theMatrix1%22%7D+-%3E%22%5B%5B+1.5%2C-0.5%2C0+%5D+%2C+%5B-0.5%2C0.44230769%2C-0.25%5D+%2C+%5B+0%2C-0.25%2C+0.25%5D%5D%22&assumption=%22FSelect%22+-%3E+%7B%7B%22MatricesOperations%22%7D%7D&assumption=%7B%22FP%22%2C+%22MatricesOperations%22%2C+%22matricesop%22%7D+-%3E+%22matrixmult%22

for i in range(5):
    x_i = x[i]
    y_hat = theta_star[0]*x_i[0] + theta_star[1]*x_i[1] + theta_star[2]*x_i[2]
    #Loss = get_loss2()
    print(f'y_hat_analytic[{i+1}]: {y_hat}, y_label[{i+1}]: {y[i]}')

xT:
[[1 1 1 1 1]
 [1 2 3 3 4]
 [2 1 2 3 5]]
xTx:
[[ 5 13 13]
 [13 39 39]
 [13 39 43]]
xTx_inverse:
[[ 1.5        -0.5         0.        ]
 [-0.5         0.44230769 -0.25      ]
 [ 0.         -0.25        0.25      ]]
theta_star:
[3.         0.44230769 1.25      ]
Loss: 6.057692307692308
y_hat_analytic[1]: 5.9423076923077005, y_label[1]: 6
y_hat_analytic[2]: 5.134615384615394, y_label[2]: 4
y_hat_analytic[3]: 6.826923076923087, y_label[3]: 7
y_hat_analytic[4]: 8.076923076923087, y_label[4]: 10
y_hat_analytic[5]: 11.01923076923078, y_label[5]: 10


In [ ]:
w1 = 0
w2 = 0
w3 = 0

def get_loss3():
    ret = 0 
    #get squared loss
    for idx in range(5):
        x_t = x[idx]
        y_pred = w1*x_t[0] + w2*x_t[1] + w3*x_t[2]
        ret += (y_pred - y[idx])*(y_pred - y[idx])
    return ret

learning_rate = 1e-2
for t in range(300):
    # 순전파 단계: 예측값 y를 계산합니다
    # a = theta_0
    # b = theta_1
    # c = theta_2
    # y = ax[0] + bx[1] + cx[2]
    #datanum = t
    #print(f'{t}th learning')
    #print(f'start with parameters {a}, {b}, {c}, learning rate {learning_rate}')

    # 손실(loss)을 계산하고 출력합니다
    loss = get_loss3()
    if(t % 100 == 0):
        print(f'loss: {loss}')

    # 손실에 따른 a, b, c의 변화도(gradient)를 계산하고 역전파합니다.
    grad_y_pred = np.zeros(3)
    for i in range(5):
        x_i = x[i]
        y_hat = w1 * x_i[0] + w2 * x_i[1] + w3 * x_i[2]
        for j in range(3):
            #grad[j] = 2*(y_hat - y)*x_i[j] for all i
            #print(f'i: {i}, j:{j}')
            #print(f"j {j} yhat {y_hat}, y[i] {y[i]}, x_i[j] {x_i[j]}")
            tmp= 2.0 * (y_hat - y[i]) * x_i[j]
            #print(f'2.0 * (y_hat - y[i]) * x_i[j] = 2*({y_hat} - {y[i]})*{x_i[j]} = {tmp}')
            grad_y_pred[j] += tmp
    
    #print(grad_y_pred)
    grad_a = grad_y_pred[0] #x_t[0] is always 1
    grad_b = grad_y_pred[1]
    grad_c = grad_y_pred[2]
    #print(f'grad: grad_a {grad_a}, grad_b {grad_b},  grad_c {grad_c}')

    # 가중치를 갱신합니다.
    w1 -= learning_rate * grad_a
    w2 -= learning_rate * grad_b
    w3 -= learning_rate * grad_c
    print(f'updated parameters: {w1}, {w2}, {w3}')
    #print("\n")


#get final loss for data 1~5
print(f'w1: {w1}, w2: {w2},w3: {w3}')
print(f'Loss: {get_loss3()}')
for i in range(5):
    x_i = x[i]
    y_hat = w1*x_i[0] + w2*x_i[1] + w3*x_i[2]  
    print(f'y_hat_numerical[{i+1}]: {y_hat}, y_label[{i+1}]: {y[i]}')




loss: 301
updated parameters: 0.74, 2.1, 2.2
updated parameters: 0.288, 0.6536, 0.6776
updated parameters: 0.653088, 1.640384, 1.710176
updated parameters: 0.4566336, 0.9571443199999999, 0.9901222399999998
updated parameters: 0.6446809344000001, 1.4195516672000001, 1.473319808
updated parameters: 0.568066257408, 1.0954948735999999, 1.1313974297599998
updated parameters: 0.6722676327936001, 1.3108216500531202, 1.3562124118323202
updated parameters: 0.6516120134240256, 1.1557454972561407, 1.192639266088755
updated parameters: 0.7158707736119502, 1.2545862583568754, 1.2960688859023892
updated parameters: 0.7211133587433463, 1.1789488446955418, 1.2167459613688645
updated parameters: 0.766121373292266, 1.222817422692035, 1.2632748624558485
updated parameters: 0.7831252418245898, 1.1844738832206967, 1.2238693339880424
updated parameters: 0.8186434811678587, 1.202353610923487, 1.2438395149717894
updated parameters: 0.840768920318301, 1.1814756676215281, 1.2234544104720875
updated parameters: 

In [ ]:
#prediction for [1,5,3]
x_test = np.array([1,5,3])

y_numeric = a* x_test[0] + b * x_test[1] + c * x_test[2]
y_converge = w1 * x_test[0] + w2 * x_test[1] + w3 * x_test[2]
y_analytic = theta_star[0]*x_test[0] + theta_star[1]*x_test[1] + theta_star[2]*x_test[2]
print(f'theta 5: {a},{b},{c}')
print(f'theta 300: {w1},{w2},{w3}')
print(f'analytic: {theta_star}')
#print(f'y_numeric: {y_numeric}, y_converge: {y_converge} y_analytic: {y_analytic}')
print(f'y_theta5: {y_numeric}, y_converge: {y_converge} y_analytic: {y_analytic}')


theta 5: 0.6446809344000001,1.4195516672000001,1.473319808
theta 300: 2.928099443895298,0.47178165138112044,1.2449361314351306
analytic: [3.         0.44230769 1.25      ]
y_theta5: 12.1623986944, y_converge: 9.021816095106292 y_analytic: 8.961538461538474
